[package]
name = "iced_glass"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/maxbergmark/iced", features = [
    "wgpu",
    "image",
    "advanced",
    "svg",
    "tokio",
], branch = "latest" }
iced_wgpu = { git = "https://github.com/maxbergmark/iced", branch = "latest" }

wgpu = { version = "27.0.1", features = [] }
bytemuck = "1.25.0"
num-traits = "0.2.19"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
itertools = "0.14.0"
cosmic-text = "0.19.0"
fontdue = "0.9.3"
msdfgen = { version = "0.2.1", features = ["ttf-parser"] }
notosans = "0.1.0"
ttf-parser = "0.18"
etagere = "0.3.0"
# freetype-rs = "0.32.0"
