[package]
name = "iced_glass"
version = "0.1.0"
edition = "2024"

[dependencies]
# iced = { version = "0.14.0", features = ["wgpu", "image"] }
iced = { git = "https://github.com/maxbergmark/iced", features = [
    "wgpu",
    "image",
    "advanced",
    "svg",
], branch = "latest" }
iced_wgpu = { git = "https://github.com/maxbergmark/iced", branch = "latest" }

wgpu = { version = "27.0.1", features = [] }
tokio = { version = "1.48.0", features = ["full"] }
bytemuck = "1.25.0"
num-traits = "0.2.19"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
itertools = "0.14.0"
