[package]
name = "basic_web"
version = "0.1.0"
authors = ["Max Bergmark <max.bergmark@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
iced_glass = { path = "../..", default-features = false }
iced = { workspace = true }
fastrand = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced = { workspace = true, features = ["fira-sans"] }
console_error_panic_hook = "0.1"
console_log = "1.0"
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
