[package]
name = "web_minimal"
version = "0.1.0"
authors = ["Max Bergmark <max.bergmark@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
iced = { git = "https://github.com/maxbergmark/iced", branch = "test/force_copy_src", features = [
    "wgpu",
    # "webgl",
    "tokio",
    "fira-sans",
    "web-colors",
], default-features = false }
fastrand = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# iced = { workspace = true, features = ["fira-sans"] }
console_error_panic_hook = "0.1"
console_log = "1.0"
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
